# Production configuration
spring:
  # Database Configuration - MySQL
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bharatshop}?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:bharatshop}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        use_sql_comments: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    open-in-view: false
  
  # Flyway Configuration - Disabled to use JPA auto-generation
  flyway:
    enabled: false
    ignore-ignored-migrations: false
    ignore-pending-migrations: false
    ignore-future-migrations: false

# Logging for production
logging:
  level:
    com.bharatshop: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId:-},%X{tenantId:-},%X{userId:-}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{traceId:-},%X{tenantId:-},%X{userId:-}] - %msg%n"
  file:
    name: logs/bharatshop.log
    max-size: 100MB
    max-history: 30

# Actuator for production monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: bharatshop
      environment: production

# Security settings
server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: 30m
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Application specific settings
app:
  tenant:
    header-name: X-Tenant-ID
    default-tenant: system
    enable-subdomain-resolution: true
  
  # Security settings
  security:
    jwt:
      secret: ${JWT_SECRET:your-very-secure-secret-key-here-change-in-production}
      expiration: 86400000 # 24 hours
    
  # Rate limiting
  rate-limit:
    enabled: true
    requests-per-minute: 100
    burst-capacity: 200
  
  # File upload settings
  upload:
    max-file-size: 10MB
    max-request-size: 50MB
    allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx
  
  # Payment configuration
  payment:
    razorpay:
      key-id: ${RAZORPAY_KEY_ID}
      key-secret: ${RAZORPAY_KEY_SECRET}
      webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
      currency: INR