server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: bharatshop-storefront
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bharatshop_storefront
    username: bharatshop
    password: bharatshop123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 1
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/bharatshop

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.bharatshop: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/storefront.log

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

# Custom application properties
app:
  name: BharatShop Storefront
  version: 1.0.0
  description: Customer-facing APIs for BharatShop
  
  tenant:
    header-name: X-Tenant-ID
    default-tenant: default
  
  security:
    jwt:
      secret: bharatshop-storefront-secret-key-change-in-production
      expiration: 86400000 # 24 hours
  
  storage:
    type: minio # or aws-s3
    minio:
      endpoint: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket-name: bharatshop-storefront
    aws:
      region: us-east-1
      bucket-name: bharatshop-storefront
  
  payment:
    razorpay:
      key-id: rzp_test_key
      key-secret: rzp_test_secret
      webhook-secret: webhook_secret

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: INFO
    com.bharatshop: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false
  
  flyway:
    validate-on-migrate: true

logging:
  level:
    root: WARN
    com.bharatshop: INFO
  file:
    name: /var/log/bharatshop/storefront.log