# Prometheus configuration for BharatShop monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'bharatshop-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # BharatShop Application
  - job_name: 'bharatshop-app'
    static_configs:
      - targets: ['bharatshop-app:8080']
    scrape_interval: 15s
    metrics_path: /actuator/prometheus
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # MySQL Database (if mysql_exporter is added)
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']
  #   scrape_interval: 30s

  # Redis (if redis_exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #   scrape_interval: 30s

  # Node Exporter (if added for system metrics)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 30s

  # MinIO (if minio metrics are enabled)
  # - job_name: 'minio'
  #   static_configs:
  #     - targets: ['minio:9000']
  #   scrape_interval: 30s
  #   metrics_path: /minio/v2/metrics/cluster

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093